
_target_: factories.pipeline_factory.pipeline_factory

steps_config:
  - TSTransformer:
      _target_: transformers.ts_transformer.CustomTransformer
      params:
        min_length: ${data_provider.params.min_length}
        with_mean: null
        with_std: False
        feature_set:
          diff:
            - True
            - median
            - True
          avg:
            - True
            - median
            - True
          rssi_left:
            - True
            - median
            - False
          rssi_right:
            - True
            - median
            - True

  - minirocket:
      _target_: sktime.transformations.panel.rocket.MiniRocketMultivariate
#      num_kernels: 10000
      max_dilations_per_kernel: 32
#      n_jobs: 16
      random_state: 1

  - standard_scaler:
      _target_: sklearn.preprocessing.StandardScaler
#      with_mean: False
#      with_std: False

  - logistic_regression:
      _target_: sklearn.linear_model.SGDClassifier
      loss: log
      penalty: l2
      # dual: False
      alpha: 0.222  # the higher the value, the stronger the regularization
      max_iter: 500
      verbose: 1
#      eta0: 0.0001
      learning_rate: optimal
      n_iter_no_change: 150
      # fit_intercept: True
      class_weight: balanced
      # solver: saga  # auto / saga
      random_state: 1

#  - logistic_regression:
#      _target_: sklearn.linear_model.LogisticRegression
#      penalty: l2
#      # dual: False
#      C: 1.0  # smaller values specify stronger regularization
#      max_iter: 100
#      # fit_intercept: True
#      class_weight: balanced
#      # solver: saga  # auto / saga
#      random_state: 1

#  - ridge_classifier:
#      _target_: sklearn.linear_model.RidgeClassifier
#      alpha: 1.0
#      # fit_intercept: True
#      class_weight: balanced
#      # solver: saga  # auto / saga
#      random_state: 1
#      normalize: True
