
_target_: factories.pipeline_factory.pipeline_factory

steps_config:
  - FeatureTransformer:
      _target_: transformers.catch_transformer.CustomTransformer
      params:
          with_mean: median
          with_std: False
          sel_feat: diff

  - CatchTransformer:
      _target_: sktime.transformations.panel.catch22.Catch22
      outlier_norm: False
      replace_nans: True

  - HistGradientBoostingClassifier:
      _target_: sklearn.ensemble.HistGradientBoostingClassifier
      loss: binary_crossentropy
      learning_rate: 0.06157763403218902  # 0.1
      max_iter: 100
      max_leaf_nodes: 31
      max_depth: null
      min_samples_leaf: 20
      l2_regularization: 0.0014145416042771236  # 0.01
      max_bins: 255  # 255
      categorical_features: null
      n_iter_no_change: 20
      random_state: 42
      verbose: 1
