
defaults:
  - override sweeper: optuna
  - override sweeper/sampler: tpe

sweeper:
  sampler:
    seed: 123
  direction:
    - maximize
    - minimize

  study_name: opti
  storage: null
  n_trials: 100
  n_jobs: 2

  search_space:
    pipeline.steps_config.2.logistic_regression.learning_rate:
      type: float
      low: 0.00001
      high: 10.0
      log: True

