
_target_: factories.pipeline_factory.pipeline_factory

steps_config:
  - FeatureTransformer:
      _target_: transformers.feature_transformer.CustomTransformer

  - HistGradientBoostingClassifier:
      _target_: sklearn.ensemble.HistGradientBoostingClassifier
      loss: binary_crossentropy
      learning_rate: 0.03678058528747944  # 0.1
      max_iter: 100
      max_leaf_nodes: 31
      max_depth: null
      min_samples_leaf: 20
      l2_regularization: 0.2788278681181583  # 0.01
      max_bins: 255  # 255
      categorical_features: null
      n_iter_no_change: 20
      random_state: 42
      verbose: 1
